### ISSUE TITLE
Empty this and store it somewhere in a temp folder ...[ DON'T DELETE CODE]

### ISSUE THREAD

**Issue by sidghimire** [sidghimire/sanoschool#45]
Just remove everything from the profile section and keep it empty we will add according to our necessity but at the moment keep it empty
<img width="357" alt="Screenshot 2023-08-06 at 15 01 53" src="https://github.com/sidghimire/sanoschool/assets/25863990/dfbdc4f8-c346-408e-9de3-76c3f9c80fd3">

When i mean remove everything just remove this section as we dont want colliding ideas
 
<img width="318" alt="Screenshot 2023-08-06 at 15 02 44" src="https://github.com/sidghimire/sanoschool/assets/25863990/d648e661-247d-4c1a-874c-84d68022e6ea">

**Comment by sabinonweb** [comment]
Have kept the code in ProfileStorage inside login
